title: alexcojocaru.github.io
description: > # this means to ignore newlines until "baseurl:"
    My GitHub site.
baseurl: ""
github_username: alexcojocaru

# Build settings
markdown: kramdown
theme: jekyll-theme-minimal
